precompile(Gurobi.cbget, (Type{Int32}, Gurobi.CallbackData, Int32, Int64,))
precompile(Gurobi.updatemodel!, (Gurobi.GurobiMathProgModel,))
precompile(Gurobi.loadproblem!, (Gurobi.GurobiMathProgModel, Base.SparseMatrix.SparseMatrixCSC{Float64, Int64}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1}, Symbol,))
precompile(Gurobi.mastercallback, (Ptr{Void}, Ptr{Void}, Int32, Ptr{Void},))
precompile(Gurobi.call, (Array{Any, 1}, Type{Gurobi.Model}, Gurobi.Env, Ptr{Void},))
precompile(Gurobi.add_qconstr!, (Gurobi.Model, Array{Int32, 1}, Array{Float64, 1}, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1}, Int8, Float64,))
precompile(Gurobi.call, (Array{Any, 1}, Type{Gurobi.Model}, Gurobi.Env, ASCIIString,))
precompile(Gurobi.call, (Type{Gurobi.Env},))
precompile(Gurobi.setquadobj!, (Gurobi.GurobiMathProgModel, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1},))
precompile(Gurobi.add_constrs!, (Gurobi.Model, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1}, Array{Int8, 1}, Array{Float64, 1},))
precompile(Gurobi._chklen, (Array{Int8, 1}, Int64,))
precompile(Gurobi.set_int_param!, (Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.add_qpterms!, (Gurobi.Model, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1},))
precompile(Gurobi.status, (Gurobi.GurobiMathProgModel,))
precompile(Gurobi.call, (Array{Any, 1}, Type{Gurobi.GurobiSolver},))
precompile(Gurobi.LinearQuadraticModel, (Gurobi.GurobiSolver,))
precompile(Gurobi.call, (Array{Any, 1}, Type{Gurobi.GurobiMathProgModel},))
precompile(Gurobi.add_rangeconstrs!, (Gurobi.Model, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1},))
precompile(Gurobi.set_dblattrarray!, (Gurobi.Model, ASCIIString, Int64, Int64, Array{Float64, 1},))
precompile(Gurobi.set_dbl_param!, (Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.delq!, (Gurobi.Model,))
precompile(Gurobi.set_intattr!, (Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.get_intattr, (Gurobi.Model, ASCIIString,))
precompile(Gurobi.get_dblattr, (Gurobi.Model, ASCIIString,))
precompile(Gurobi.call, (Type{Gurobi.GurobiMathProgModel}, Gurobi.Model, Symbol, Bool, Array{Float64, 1}, Array{Float64, 1}, Void, Void, Void, Void,))
precompile(Gurobi.add_vars!, (Gurobi.Model, Array{Int8, 1}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1},))
precompile(Gurobi.update_model!, (Gurobi.Model,))
precompile(Gurobi.get_error_msg, (Gurobi.Env,))
precompile(Gurobi.get_dblattrarray!, (Array{Float64, 1}, Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.optimize, (Gurobi.Model,))
precompile(Gurobi.setmathprogcallback!, (Gurobi.GurobiMathProgModel,))
precompile(Gurobi.set_charattrarray!, (Gurobi.Model, ASCIIString, Int64, Int64, Array{Char, 1},))
precompile(Gurobi.setparam!, (Gurobi.Env, ASCIIString, Int64,))
precompile(Gurobi.setparam!, (Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.free_model, (Gurobi.Model,))
precompile(Gurobi.set_dbl_param!, (Gurobi.Env, ASCIIString, Int64,))
precompile(Gurobi.add_rangeconstrs!, (Gurobi.Model, Base.SparseMatrix.SparseMatrixCSC{Float64, Int64}, Array{Float64, 1}, Array{Float64, 1},))
precompile(Gurobi.get_charattrarray!, (Array{Int8, 1}, Gurobi.Model, ASCIIString, Int64,))
precompile(Gurobi.optimize!, (Gurobi.GurobiMathProgModel,))
precompile(Gurobi.add_constrs_t!, (Gurobi.Model, Base.SparseMatrix.SparseMatrixCSC{Float64, Int64}, Array{Int8, 1}, Array{Float64, 1},))
precompile(Gurobi.set_int_param!, (Gurobi.Env, ASCIIString, Int64,))
precompile(Gurobi._chklen, (Array{Float64, 1}, Int64,))
precompile(Gurobi.add_constrs!, (Gurobi.Model, Base.SparseMatrix.SparseMatrixCSC{Float64, Int64}, Array{Int8, 1}, Array{Float64, 1},))
precompile(Gurobi.addquadconstr!, (Gurobi.GurobiMathProgModel, Array{Int32, 1}, Array{Float64, 1}, Array{Int32, 1}, Array{Int32, 1}, Array{Float64, 1}, Char, Float64,))
precompile(Gurobi.setsense!, (Gurobi.GurobiMathProgModel, Symbol,))
precompile(Gurobi.setvartype!, (Gurobi.GurobiMathProgModel, Array{Symbol, 1},))
precompile(Gurobi.free_env, (Gurobi.Env,))
precompile(Gurobi.add_constrs!, (Gurobi.Model, Array{Int64, 1}, Array{Int64, 1}, Array{Float64, 1}, Array{Int8, 1}, Array{Float64, 1},))
precompile(Gurobi.add_rangeconstrs!, (Gurobi.Model, Array{Int64, 1}, Array{Int64, 1}, Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1},))
precompile(Gurobi.getsolution, (Gurobi.GurobiMathProgModel,))
precompile(Gurobi.set_sense!, (Gurobi.Model, Symbol,))
precompile(Gurobi.getobjval, (Gurobi.GurobiMathProgModel,))
